import { ArrowUpRight, Camera as Instagram, ChevronRight, Clock3, MapPin, Star, UtensilsCrossed } from 'lucide-react';

const menu = [
  { name: 'Sunday Roast Mixed', note: 'Frango assado, legumes da estação, batatas crocantes e gravy', price: '£18.50', pos: '70% 52%' },
  { name: 'Full English Breakfast', note: 'O clássico inglês, servido durante toda a manhã', price: '£14.00', pos: '82% 38%' },
  { name: 'Crushed Avocado & Salmon', note: 'Sourdough, abacate, salmão defumado e ovo poché', price: '£13.50', pos: '62% 65%' },
  { name: 'Pollo Asado Con', note: 'Frango suculento assado lentamente com acompanhamentos da casa', price: '£16.00', pos: '74% 48%' },
];
const drinks = ['Spanish iced latte', 'Pomegranate drink', 'Oreo milkshake', 'Chai latte', 'Cappuccino'];

export default function Home() {
  return <main>
    <header className="topbar"><a href="#inicio" className="brand" aria-label="Hour House Bistro — início"><span className="brand-mark">HH</span><span>Hour House <em>Bistro</em></span></a><nav aria-label="Navegação principal"><a href="#cardapio">Cardápio</a><a href="#sobre">Sobre</a><a href="#avaliacoes">Avaliações</a></nav><a className="pill pill-light" href="https://www.instagram.com/hourhousebistro/" target="_blank" rel="noreferrer"><Instagram size={17}/> @hourhousebistro</a></header>
    <section className="hero" id="inicio"><img src="/images/hero-roast.png" alt="Sunday roast do Hour House Bistro"/><div className="hero-shade"/><div className="hero-content"><p className="eyebrow">Seu bistrô de bairro em East London</p><h1>Good food.<br/><i>Good hours.</i></h1><p className="hero-copy">Pratos generosos, café bem tirado e uma mesa sempre pronta para você.</p><div className="hero-actions"><a className="pill pill-cream" href="#cardapio">Ver cardápio <ChevronRight size={17}/></a><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Salmon+Ln%2C+London+E14+7PG" target="_blank" rel="noreferrer">Como chegar <ArrowUpRight size={16}/></a></div></div><div className="rating-card"><span className="rating-number">4,4</span><span className="stars" aria-label="4,4 de 5 estrelas">★★★★★</span><span>287 avaliações</span></div></section>
    <section className="quick-info" aria-label="Informações principais"><div><Clock3/><span><small>Hoje</small>Aberto até 22:00</span></div><div><MapPin/><span><small>Encontre-nos</small>Salmon Ln, London E14 7PG</span></div><div><UtensilsCrossed/><span><small>Serviço</small>No local · Para viagem</span></div><div className="price"><small>Preço médio</small><strong>£10–20</strong> por pessoa</div></section>
    <section className="intro" id="sobre"><p className="section-kicker">Uma pausa bem servida</p><div><h2>Comida que conforta.<br/>Um lugar que acolhe.</h2><p>Do café da manhã ao Sunday Roast, preparamos cada prato para chegar à mesa fresco, quente e sem pressa. Um bistrô local, descontraído e feito para voltar.</p></div></section>
    <section className="menu-section" id="cardapio"><div className="section-head"><div><p className="section-kicker">Favoritos da casa</p><h2>Do nosso cardápio</h2></div><p>Receitas honestas, porções generosas e ingredientes preparados na hora.</p></div><div className="menu-grid">{menu.map((item,index)=><article className={`menu-card card-${index+1}`} key={item.name}><div className="menu-photo"><img src="/images/hero-roast.png" alt="" style={{objectPosition:item.pos}}/></div><div className="menu-copy"><div><span>{index<2?'Mais pedido':'Da casa'}</span><h3>{item.name}</h3><p>{item.note}</p></div><strong>{item.price}</strong></div></article>)}</div><div className="drinks"><span>Para acompanhar</span>{drinks.map(drink=><span key={drink}>{drink}</span>)}</div></section>
    <section className="review-section" id="avaliacoes"><div className="review-aside"><Star fill="currentColor"/><span>4,4 no Google</span><small>287 avaliações</small></div><blockquote>“A comida chegou fresca e quente, o ambiente era descontraído e acolhedor. O Chicken Roast e o steak com mash estavam muito melhores do que esperávamos pelo preço.”<footer>— Visitante recente</footer></blockquote></section>
    <section className="visit"><div className="visit-copy"><p className="section-kicker">Venha nos visitar</p><h2>Seu próximo prato favorito está logo ali.</h2><div className="address"><MapPin/><span>Salmon Lane<br/>London E14 7PG<br/>Reino Unido</span></div><a className="pill pill-dark" href="https://www.google.com/maps/search/?api=1&query=Salmon+Ln%2C+London+E14+7PG" target="_blank" rel="noreferrer">Abrir no mapa <ArrowUpRight size={17}/></a></div><a className="insta-card" href="https://www.instagram.com/hourhousebistro/" target="_blank" rel="noreferrer"><Instagram/><span>Acompanhe nossa cozinha</span><strong>@hourhousebistro</strong><small>Novidades, pratos do dia e bastidores <ArrowUpRight size={14}/></small></a></section>
    <footer className="footer"><div className="brand"><span className="brand-mark">HH</span><span>Hour House <em>Bistro</em></span></div><p>Good food. Good hours. Good company.</p><a href="https://www.instagram.com/hourhousebistro/" target="_blank" rel="noreferrer"><Instagram size={18}/> Instagram</a></footer>
  </main>;
}
