'use client';
import { ArrowUpRight, Camera, ChevronRight, Clock3, MapPin, Star, UtensilsCrossed } from 'lucide-react';
import { useState } from 'react';

type Lang='pt'|'en'|'es';
const copy={
 pt:{nav:['Cardápio','Sobre','Avaliações'],eyebrow:'Seu bistrô de bairro em East London',title:['Good food.','Good hours.'],lead:'Pratos generosos, café bem tirado e uma mesa sempre pronta para você.',menu:'Ver cardápio',directions:'Como chegar',today:'Hoje',open:'Aberto até 22:00',find:'Encontre-nos',service:'Serviço',eat:'No local · Para viagem',average:'Preço médio',person:'por pessoa',pause:'Uma pausa bem servida',welcome:['Comida que conforta.','Um lugar que acolhe.'],about:'Do café da manhã ao House Roast, preparamos cada prato para chegar à mesa fresco, quente e sem pressa. Um bistrô local, descontraído e feito para voltar.',fav:'Cardápio completo',ourMenu:'Escolha o seu momento',menuIntro:'Todos os pratos e bebidas disponíveis, organizados para você explorar com calma.',google:'4,4 no Google',reviews:'287 avaliações',quote:'“A comida chegou fresca e quente, o ambiente era descontraído e acolhedor. O Chicken Roast e o steak com mash estavam muito melhores do que esperávamos pelo preço.”',visitor:'— Visitante recente',visit:'Venha nos visitar',next:'Seu próximo prato favorito está logo ali.',map:'Abrir no mapa',follow:'Acompanhe nossa cozinha',news:'Novidades, pratos do dia e bastidores',note:'Preços e disponibilidade podem variar. Consulte a equipe no local.'},
 en:{nav:['Menu','About','Reviews'],eyebrow:'Your neighbourhood bistro in East London',title:['Good food.','Good hours.'],lead:'Generous plates, properly made coffee and a table that is always ready for you.',menu:'View the menu',directions:'Get directions',today:'Today',open:'Open until 10 pm',find:'Find us',service:'Service',eat:'Dine-in · Takeaway',average:'Average price',person:'per person',pause:'A proper pause',welcome:['Comforting food.','A warm welcome.'],about:'From breakfast to our House Roast, every plate arrives fresh, hot and unhurried. A relaxed local bistro made for coming back to.',fav:'Full menu',ourMenu:'Choose your moment',menuIntro:'Every dish and drink currently available, arranged so you can browse at your own pace.',google:'4.4 on Google',reviews:'287 reviews',quote:'“The food arrived fresh and hot, and the atmosphere felt relaxed and welcoming. The Chicken Roast and steak with mash were much better than expected for the price.”',visitor:'— Recent guest',visit:'Come and visit',next:'Your next favourite plate is just around the corner.',map:'Open in Maps',follow:'Follow our kitchen',news:'New dishes, daily specials and behind the scenes',note:'Prices and availability may vary. Please check with our team.'},
 es:{nav:['Menú','Nosotros','Reseñas'],eyebrow:'Tu bistró de barrio en East London',title:['Buena comida.','Buenos momentos.'],lead:'Platos generosos, café bien preparado y una mesa siempre lista para ti.',menu:'Ver el menú',directions:'Cómo llegar',today:'Hoy',open:'Abierto hasta las 22:00',find:'Encuéntranos',service:'Servicio',eat:'En el local · Para llevar',average:'Precio medio',person:'por persona',pause:'Una pausa bien servida',welcome:['Comida que reconforta.','Un lugar que acoge.'],about:'Del desayuno al House Roast, cada plato llega fresco, caliente y sin prisas. Un bistró local y relajado al que querrás volver.',fav:'Menú completo',ourMenu:'Elige tu momento',menuIntro:'Todos los platos y bebidas disponibles, organizados para que los explores con calma.',google:'4,4 en Google',reviews:'287 reseñas',quote:'“La comida llegó fresca y caliente, y el ambiente era relajado y acogedor. El Chicken Roast y el steak con puré superaron nuestras expectativas por el precio.”',visitor:'— Cliente reciente',visit:'Ven a visitarnos',next:'Tu próximo plato favorito está a la vuelta de la esquina.',map:'Abrir en Maps',follow:'Sigue nuestra cocina',news:'Novedades, platos del día y detrás de cámaras',note:'Los precios y la disponibilidad pueden variar. Consulta con el equipo.'}
};

const categories=[
 {n:['Brunch','Brunch','Brunch'],items:[['Pancakes','£10'],['Veggie Brunch','£13'],['Crushed Avocado & Smoked Salmon','£13'],['Classic French Toast','£10'],['House Special','£16'],['Full House','£12'],['Fuller House','£16'],['Carnivore Breakfast','£17']]},
 {n:['Pratos principais','Mains','Platos principales'],items:[['Aberdeen Black Angus Steak','£20'],['½ Chicken on the Grill','£12'],['House Burger','£10'],['Blue Cheese Burger','£12'],['Honey Glazed Salmon','£13'],['Fish & Chips','£10'],['House Pie','£13'],["Bangers & Mash",'£10'],['Beef Stew','£12'],['Jacket Potato','£8'],["Shepherd’s Pie",'£15'],['Lasagna','£16']]},
 {n:['House Roast','House Roast','House Roast'],sub:'Served with mash, gravy, roasted vegetables, Yorkshire puddings & roast potatoes',items:[['Slow Cooked Lamb','£16'],['Chicken Roast','£13'],['Mixed Roast','£18']]},
 {n:['Saladas & massas','Salads & pasta','Ensaladas y pasta'],items:[['Chicken Caesar','£8'],['Roasted Chicken & Sweetcorn','£8'],['Sweet Heat Salmon Salad','£12'],['Loaded Veg Salad','£6'],['Beetroot, Feta & Walnut','£8'],['Chicken & Sweetcorn Pasta','£8'],['Tuna Mayo & Sweetcorn Pasta','£5'],['Spag Bol','£10'],['Loaded Veg Pasta','£6']]},
 {n:['Petiscos','Picky bits','Para picar'],items:[['Fries','£2'],['Sweet Potato Fries','£2.50'],['Wedges','£2'],['Mash Potato','£3.50'],['Roasted Vegetables','£2.50'],['Garlic Bread','£3'],['Mac & Cheese','£4'],['Mac & Cheese Bites','£3'],['Halloumi & Chilli Jam','£4'],['Crunchy Shrimp Cocktail','£5']]},
 {n:['Para crianças','Kids','Para niños'],items:[['Kids Bangers & Mash','£6.50'],['Kids Roast Chicken','£6.50'],['Kids Fish Fingers','£5.20'],['Grilled Wings & Chips','£3.90']]},
 {n:['Sanduíches & doces','Sandwiches & pastries','Sándwiches y dulces'],items:[['Panini','from £6.50'],['Seeded Panini','from £6.50'],['Bagel','from £5.20'],['Tiger Bloomer','from £7.80'],['The Full English','£10.40'],['Buttered Croissant','£3.30'],['Pain au Chocolat','£3.30'],['Almond Croissant','£3.30'],['Cinnamon Roll','£3.30']]},
 {n:['Cafés quentes','Hot coffee','Cafés calientes'],items:[['Karak Coffee','£2'],['Latte','£5.10'],['Cappuccino','£5.10'],['Americano','£5.10'],['Flat White','£4.70'],['Mocha','£5.60'],['Matcha Latte','£5.60'],['Espresso','£3.60'],['Double Espresso','£3.90'],['Hot Chocolate','£4.60']]},
 {n:['Cafés gelados','Iced coffee','Cafés fríos'],items:[['Spanish Iced Latte','£4.70'],['Iced Americano','£5.10'],['Iced Matcha Latte','£5.50'],['Iced Chai','£5.60'],['Iced Latte','£6'],['Iced Mocha','£6.10'],['Caramel Espresso Crème','£6.10']]},
 {n:['Chás, sucos & smoothies','Tea, juices & smoothies','Tés, zumos y smoothies'],items:[['Earl Grey','£6.10'],['Peppermint Tea','£3.30'],['Camomile Tea','£3.30'],['Lemon & Ginger Tea','£3.30'],['English Breakfast Tea','£3.30'],['Green Tea','£3.30'],['Fresh Lemonade','£3.50'],['Apple Juice','£3.30'],['Orange Juice','£3.30'],['Mango Juice','£3.30'],['Guava Juice','£3.30'],['Berry Juice','£3.30'],['Lychee Juice','£3.30'],['Green Smoothie','£4.50'],['Tropical Mix Smoothie','£4.50'],['Tiramisu Milkshake','£6.75']]}
];

export default function Home(){const [lang,setLang]=useState<Lang>('pt');const t=copy[lang];const li=lang==='pt'?0:lang==='en'?1:2;return <main>
 <header className="topbar"><a href="#inicio" className="brand"><span className="brand-mark">HH</span><span>Hour House <em>Bistro</em></span></a><nav>{t.nav.map((x,i)=><a key={x} href={['#cardapio','#sobre','#avaliacoes'][i]}>{x}</a>)}</nav><div className="header-actions"><div className="language" aria-label="Language">{(['pt','en','es'] as Lang[]).map(x=><button className={lang===x?'active':''} onClick={()=>setLang(x)} key={x}>{x==='en'?'EN·UK':x.toUpperCase()}</button>)}</div><a className="pill pill-light" href="https://www.instagram.com/hourhousebistro/" target="_blank" rel="noreferrer"><Camera size={17}/><span>@hourhousebistro</span></a></div></header>
 <section className="hero" id="inicio"><img src="/images/hero-roast.png" alt="Hour House Bistro Sunday roast"/><div className="hero-shade"/><div className="hero-content"><p className="eyebrow">{t.eyebrow}</p><h1>{t.title[0]}<br/><i>{t.title[1]}</i></h1><p className="hero-copy">{t.lead}</p><div className="hero-actions"><a className="pill pill-cream" href="#cardapio">{t.menu}<ChevronRight size={17}/></a><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=129+Salmon+Ln%2C+London+E14+7PG" target="_blank" rel="noreferrer">{t.directions}<ArrowUpRight size={16}/></a></div></div><div className="rating-card"><span className="rating-number">4.4</span><span className="stars">★★★★★</span><span>{t.reviews}</span></div></section>
 <section className="quick-info"><div><Clock3/><span><small>{t.today}</small>{t.open}</span></div><div><MapPin/><span><small>{t.find}</small>129 Salmon Ln, London E14 7PG</span></div><div><UtensilsCrossed/><span><small>{t.service}</small>{t.eat}</span></div><div className="price"><small>{t.average}</small><strong>£10–20</strong>{t.person}</div></section>
 <section className="intro" id="sobre"><p className="section-kicker">{t.pause}</p><div><h2>{t.welcome[0]}<br/>{t.welcome[1]}</h2><p>{t.about}</p></div></section>
 <section className="menu-section" id="cardapio"><div className="section-head"><div><p className="section-kicker">{t.fav}</p><h2>{t.ourMenu}</h2></div><p>{t.menuIntro}</p></div><div className="category-tabs">{categories.map(c=><a href={'#cat-'+c.n[1].replaceAll(' ','-')} key={c.n[1]}>{c.n[li]}</a>)}</div><div className="full-menu">{categories.map(c=><section className="menu-category" id={'cat-'+c.n[1].replaceAll(' ','-')} key={c.n[1]}><h3>{c.n[li]}</h3>{c.sub&&<p className="cat-sub">{c.sub}</p>}<div>{c.items.map(i=><article key={i[0]}><span>{i[0]}</span><strong>{i[1]}</strong></article>)}</div></section>)}</div><p className="menu-note">{t.note}</p></section>
 <section className="review-section" id="avaliacoes"><div className="review-aside"><Star fill="currentColor"/><span>{t.google}</span><small>{t.reviews}</small></div><blockquote>{t.quote}<footer>{t.visitor}</footer></blockquote></section>
 <section className="visit"><div className="visit-copy"><p className="section-kicker">{t.visit}</p><h2>{t.next}</h2><div className="address"><MapPin/><span>129 Salmon Lane<br/>London E14 7PG<br/>United Kingdom</span></div><a className="pill pill-dark" href="https://www.google.com/maps/search/?api=1&query=129+Salmon+Ln%2C+London+E14+7PG" target="_blank" rel="noreferrer">{t.map}<ArrowUpRight size={17}/></a></div><a className="insta-card" href="https://www.instagram.com/hourhousebistro/" target="_blank" rel="noreferrer"><Camera/><span>{t.follow}</span><strong>@hourhousebistro</strong><small>{t.news}<ArrowUpRight size={14}/></small></a></section>
 <footer className="footer"><div className="brand"><span className="brand-mark">HH</span><span>Hour House <em>Bistro</em></span></div><p>Good food. Good hours. Good company.</p><a href="https://www.instagram.com/hourhousebistro/" target="_blank" rel="noreferrer"><Camera size={18}/> Instagram</a></footer>
 </main>}
